name = "JWAS"
uuid = "c9a035f4-d403-5e6b-8649-6be755bc4798"
authors = ["Hao Cheng <qtlcheng@ucdavis.edu>"]
version = "2.0.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Kronecker = "2c470bb0-bcc8-11e8-3dad-c9649493f05e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CSV = "0.5, 0.6, 0.7, 0.8, 0.10"
DataFrames = "0.19, 0.20, 0.21, 0.22, 1.5.0"
DelimitedFiles = "1.9.1"
Distributions = "0.21, 0.22, 0.23, 0.24, 0.25"
ForwardDiff = "0.10"
GSL = "1.0.1"
HTTP = "1.10.19"
Kronecker = "0.5.5"
Plots = "1.41.1"
ProgressMeter = "1.0, 1.1, 1.2"
Revise = "3.9.0"
StatsBase = "0.30, 0.31, 0.32, 0.33"
julia = "1"
